dist: trusty
language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20.0

addons:
  postgresql: '9.6'

env:
  global:
    - MIX_ENV=test
    - PRONTO_PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST

before_script:
- mix do ecto.create, ecto.migrate
- rvm install ruby-2.3.1
- gem install pronto-credo

script:
  - PRONTO_GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN pronto run -f github_pr -c origin/master
  - mix coveralls.travis

cache:
 directories:
  - /home/travis/.rvm/
  - _build
  - deps